[package]
name = "calm-ops"
version = "0.1.0"
authors = ["SLUCHABLUB"]
edition = "2024"

[dependencies]
num = "0.4.3"
paste = "1.0.15"
# TODO: Change to normal dependency
calm-ops-macros = { path = "calm-ops-macros" }

[dev-dependencies]
proptest = { version = "1.8.0", features = [ "attr-macro" ] }
